# Generated by Django 5.1.6 on 2025-02-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_job_vacancy_job_description_job_experience_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
    ]
